import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Navbar from "@/component/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <div>

                <body className={inter.className}>
                    <Navbar/>
                    <div>
                        {children}
                    </div>
                </body>

            </div>
        </html>
    );
}
